= Referências Bibliográficas
CAMat <camat.usp@gmail.com>
:toc: left
:toc-title: Conteúdos
:favicon: assets/favicon.svg
:stylesheet: assets/styles.css
:hide-uri-scheme:

image:https://img.shields.io/github/stars/camat-usp/Referencias-Bibliograficas?style=social[GitHub, link=https://github.com/camat-usp/Referencias-Bibliograficas]
image:https://img.shields.io/twitter/follow/CAMatRadical?style=social[Twitter, link=https://twitter.com/CAMatRadical/]

Reunimos neste site alguns links de download dos livros comumente utilizados em 
disciplinas relacionadas aos cursos do IME - USP.

As informações foram obtidas através do JupiterWeb, na relação bibliográfica de
cada disciplina, e de colaborações através 
https://forms.gle/ETVd3qDpj9XjuC3C6[deste formulário].

[quote,Aaron Swartz,Julho de 2008]
____
Aqueles com acesso a esses recursos -- estudantes, bibliotecários, cientistas 
-- a vocês foi dado um privilégio. Vocês começam a se alimentar nesse banquete 
de conhecimento, enquanto o resto do mundo está bloqueado. Mas vocês não 
precisam -- na verdade, moralmente, não podem -- manter este privilégio para 
vocês mesmos. Vocês têm um dever de compartilhar isso com o mundo.
____

Confira o link:manifesto.html[manifesto na integra]!

