= Atividades Online Durante a Quarentena
CAMat <camat.usp@gmail.com>
:favicon: ./favicon.svg
:toc: macro
:toc-title: Conteúdos
:note-caption: Nota
:icons: font
:stylesheet: styles.css
:hide-uri-scheme:

Com a determinação da CRUESP, que suspendeu temporariamente as atividades 
escolares presenciais a partir de terça-feira (17/03), passaram a ser adotadas 
alternativas online para dar continuidade às disciplinas.

https://google.com

Sabendo que estas medidas foram tomadas às pressas e visando auxiliar as(os) 
estudantes, organizamos este site reunindo informações de diversas disciplinas, 
facilitando o acesso, visto que estas não estão todas numa plataforma comum.

As informações foram obtidas através de contato com professores via e-mail e 
resposta do formulário divulgado pelo CAMat à comunidade estudantil do IME. 
Por isso, pedimos compreensão de todas(os) caso não encontrem neste documento 
alguma disciplina ou informação específica. Caso queira colaborar com conteúdo, 
https://qrgo.page.link/ENFtn[acesse o formulário].

O CAMat reforça que o e-mail institucional é o canal de comunicação comumente 
utilizado pelos docentes e, portanto, em momento como este, mais do que antes, 
se faz necessário o uso; cheque diariamente a sua caixa de entrada!

[NOTE]
Dúvidas? Leia o 
https://camat-usp.github.io/Atividades-Online-Durante-a-Quarentena/faq.html[F.A.Q.]?

[NOTE]
Você não tem suporte técnico adequado para acompanhar as atividades?
https://qrgo.page.link/DRMk5[Comunique o CAMat!]

[NOTE]
Quer contribuir com esse site? Acesse 
https://github.com/camat-usp/Atividades-Online-Durante-a-Quarentena[nossa página no GitHub]!

toc::[]

